### ISSUE TITLE
Policy for Administrator role in Transifex

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#110]
* What are the criteria for being Administrator?
* Can I be made an Administrator?

https://www.transifex.com/OpenDataServices/

**Comment by jpmckinney** [comment]
@timgdavies Please make me a Transifex administrator.

**Comment by timgdavies** [comment]
@jpmckinney You are a [maintainer and team manager](https://docs.transifex.com/teams/understanding-user-roles) for all the projects relating to OCDS.

At the moment we have a number of other Open Data Services projects in that account - so we need to separate out OCDS translations to their own organisation in order to make you a full administrator. 

However, before we do that I want to check on whether we might be changing our tooling for translation based on upcoming conversations with @ColinMaudry. In particular, I've been exploring https://crowdin.com/ for it's support for in-context translation, responding to one of the key concerns raised in our workshop on translation last year.

**Comment by jpmckinney** [comment]
Sounds good. At any rate, maintainer/manager is sufficient given the situation.
