### ISSUE TITLE
GitHub: Direct commits

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#22]
In what case would a contributor commit directly to the default branch instead of opening a PR?

Related #21

**Comment by jpmckinney** [comment]
If we decide there is no reason to commit directly, we should enable "Require pull request reviews before merging" on all default branches.

**Comment by jpmckinney** [comment]
I noticed "Require pull request reviews before merging" has been enabled on more repositories, but we should agree that here first.

**Comment by timgdavies** [comment]
The cases where I've committed direct have been where the fix is really minor typos etc. in extensions, and the overhead of the pull-request & review process is overkill. 

As we have not had full time software development / schema development cover (and potentially still don't have that 100% assuming you will have travel etc.) - requiring independent review for all changes may cause some bottlenecks for minor changes. 

My sense is that there is a trade off between best practice process and the benefits vs.  overheads this brings to components of differing levels of complexity - and we need to be careful about where we apply this. That said, I think we are now reaching a level of complexity across the OCDS standard repos which can justify the best practices.

**Comment by jpmckinney** [comment]
I don't think we need "Require pull request reviews before merging" as I think it's okay to self-merge a simple change (where the author only created the PR to check that they didn't accidentally break things).

The other setting, "Require status checks to pass before merging", also prevents direct commits. So far, I find that having to create PRs slows me down when I'm actively developing code and making frequent commits. If others find it to be overhead, we can disable it, as I think we can trust we won't be: (a) making direct commits irresponsibly or (b) merging branches that are failing.

**Comment by timgdavies** [comment]
Pinging @edugomez and @Bjwebb for views also

**Comment by jpmckinney** [comment]
I'm disabling "Require pull request reviews before merging" as it's too annoying. We can change back if anyone contributes a good argument.

**Comment by jpmckinney** [comment]
We've effectively disabled direct commits for a month now, so closing - though we can always have a discussion at any time.
