### ISSUE TITLE
Search is out of date

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard-development-handbook#220]
Some search results lead to pages that do not exist, e.g. the first result in [this search](https://ocds-standard-development-handbook.readthedocs.io/en/latest/search/?q=community+translation&check_keywords=yes&area=default#).

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refresh standard development handbook search index](https://trello.com/c/rUljZxV6/99-refresh-standard-development-handbook-search-index)

**Comment by jpmckinney** [comment]
It's a bug in ReadTheDocs: https://github.com/pypa/packaging.python.org/issues/567 Looking into it.

**Comment by jpmckinney** [comment]
Works now: https://ocds-standard-development-handbook.readthedocs.io/en/latest/search.html?q=community+translation&check_keywords=yes&area=default

The solution was to use the html builder instead of the dirhtml builder. However, this broke most URLs, since URLs like .../search/ are now .../search.html. This is only an issue if we link to the handbook from outside the handbook (I'll fix all those links from GitHub repos).
