### ISSUE TITLE
ReadTheDocs deployment documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-development-handbook#8]
`public-private-partnerships` and this repo have ReadTheDocs integrations.

* [x] Why does `public-private-partnerships` have two ReadTheDocs webhooks?
* [x] Does `public-private-partnerships` even use ReadTheDocs? I thought we built it differently.
* [x] Document how we configure ReadTheDocs

**Comment by Bjwebb** [comment]
> Why does `public-private-partnerships` have two ReadTheDocs webhooks?

Because we were using ReadTheDocs. We're not any more. I've removed the webhooks, and redirected the ReadTheDocs docs to the new location.

**Comment by Bjwebb** [comment]
Remaining todo on this issue: document how we configure readthedocs for this repo.

**Comment by jpmckinney** [comment]
I renamed the issue to reflect the remaining item. (I had originally written the bullet as how we configured ReadTheDocs.io, but it's also good to know how we configured our deployment of the software.)

**Comment by Bjwebb** [comment]
How we configured ReadTheDocs.io is in the README https://github.com/open-contracting/standard-development-handbook#building-on-readthedocs which is inherited from our sphinx-base repo https://github.com/OpenDataServices/sphinx-base, which where the config for the repo comes from.

I think we should:
- [ ] Update the README of this repo to say what it is (rather than the current info that is all from sphinx-base)
- [ ] Add a sentence to the README saying that the config in the repo comes from sphinx-base
- [ ] Add a page/section to the docs about ReadTheDocs.

**Comment by Bjwebb** [comment]
I think this is covered in https://github.com/open-contracting/standard-development-handbook/pull/45

**Comment by jpmckinney** [comment]
Just a note: I prefer to add e.g. `closes #8` to a PR description, and to leave issues open until merged. Merging the PR will automatically close the issue if that text is in the PR description. Otherwise, if we close the issue, and then close the PR without merging, the issue is closed without being fixed.
